### PR TITLE
feat: Defaults to MySQL 8

### PR DESCRIPTION
**Pull request by jsbroks**

### CODE REVIEW

**Comment by davidwallacejackson** [comment]
I would really like to turn this on, but maybe we should wait until https://wandb.atlassian.net/browse/WB-9250 is resolved? Anni said he was going to put Maddy on it this week.

**Comment by jsbroks** [comment]
@davidwallacejackson its enabled in aws https://github.com/wandb/terraform-aws-wandb/pull/20

**Comment by davidwallacejackson** [comment]
> @davidwallacejackson its enabled in aws [wandb/terraform-aws-wandb#20](https://github.com/wandb/terraform-aws-wandb/pull/20)

Fair enough lol

**Review by davidwallacejackson — APPROVED** [review]

**Comment by jsbroks** [comment]
This PR is included in version 1.1.0 :tada:

**Pull request merged**
