### PR TITLE
fix: Amend resource requests and limits

### PR DESCRIPTION
**Pull request by gls4**
This PR amends the resource requests to reasonable values based on behavior seen in the wild, and sets limits to null.

### CODE REVIEW

**Review by flamarion — CHANGES_REQUESTED** [review]
Shouldn't be a `fix` instead `feat`? 
A `feat` will do a `minor` release instead of a `patch` release.

**Comment by gls4** [comment]
> Shouldn't be a `fix` instead `feat`?
> A `feat` will do a `minor` release instead of a `patch` release.

Good call. Amending.

**Review by flamarion — APPROVED** [review]
🚢 it

**Comment by jsbroks** [comment]
This PR is included in version 1.19.1 :tada:

**Pull request merged**
